### ISSUE TITLE
Upgrade references to the general text modules

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/Qualification-DDI-CYP2C19#2]
Replace all refs to the general text modules with tag **v1.1**, e.g.
https://raw.githubusercontent.com/Open-Systems-Pharmacology/Qualification-text-modules/v1.1/OSPS_Introduction.md

**Comment by PavelBal** [comment]
Why not just to use the link to the master branch, e.g., https://github.com/Open-Systems-Pharmacology/Qualification-text-modules/blob/master/OSPS_Introduction.md ?

**Comment by Yuri05** [comment]
Because it's a living working copy and might change any time.
Reports might become not reproducible or even crash.

**Comment by PavelBal** [comment]
Fixed.
